Update send-message.md
broidHQ/broid-docs pull request #9
Opened 2017-09-01 16:52 UTC by killix

2017-09-06 01:19 UTC, killix commented
ping @dustinblackman

2017-09-07 02:47 UTC, dustinblackman requested changes
May need to update schemas as well. I think I remember having a problem where I did this and schemas complained.

2017-09-07 02:47 UTC, dustinblackman approved these changes
Oops, wrong button. Approved :rocket:

2017-09-14 15:37 UTC, broidy approved these changes

2017-09-14 15:37 UTC, merged